#UI tests execution configuration
environmentName=QA
implicitTimeWait=15
explicitTimeWait=15
sleepWaitTime=2
pageLoadTimeWait=30
width=1920
height=1200

# CHROME or FIREFOX OR EDGE
browser=CHROME

# Selenium Grid URL
seleniumHubUrl=http://selenium-hub
seleniumHubPort=4444

# here we can see the Chrome browser and chrome driver for each version: https://chromedriver.chromium.org/downloads
chromeDriverVersion=114.0

# Downloads folder
downloads=src/test/resources/downloads/

# Browser logs
browserLogs=false

# Incognito mode
incognitoMode=true

# Headless Mode configuration
headlessMode=false