plugins {
    id 'java'
    id "org.sonarqube" version "7.0.1.6134"
    id 'jacoco'
}

group = 'com.miasoftnanus.automation.core'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

jacocoTestReport {
    reports {
        xml.required = true // Crucial for SonarQube
        html.required = true
    }
}

sonarqube {
    properties {
        property "sonar.coverage.jacoco.xmlReportPaths",
                layout.buildDirectory.file("reports/jacoco/test/jacocoTestReport.xml").map { it.asFile.absolutePath }.get()
    }
}

test {
    useJUnitPlatform()
}