plugins {
    id 'java'
    id "org.sonarqube" version "7.0.1.6134"
}

group = 'com.miasoftnanus.automation.core'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

subprojects {
    apply plugin: 'jacoco'
    apply plugin: 'org.sonarqube'

    tasks.withType(JacocoReport).configureEach {
        reports {
            xml.required = true
        }
    }

    tasks.matching { it.name == 'sonar' }.configureEach {
        dependsOn tasks.matching { it.name == 'jacocoTestReport' }
    }

    sonarqube {
        properties {
            property 'sonar.coverage.jacoco.xmlReportPaths',
                    layout.buildDirectory.file("reports/jacoco/test/jacocoTestReport.xml").get().asFile.absolutePath
        }
    }
}

test {
    useJUnitPlatform()
}